### PR TITLE
Add a missing return in a default value function

### PR DESCRIPTION
**Pull request by jklein24**

### CODE REVIEW

**Comment by morethanreal** [comment]
Nice, can you add a test case and also see why tests are failing? I think I fixed them such that they're all passing yesterday.

**Comment by cdata** [comment]
Tests appear to be failing because CI Runner needs to be kicked ;)

**Comment by jklein24** [comment]
Yeah the tests all pass locally for me.

**Comment by morethanreal** [comment]
ugh, lgtm

**Pull request merged**
