### PR TITLE
Use flex-auto to fix IE

### PR DESCRIPTION
**Pull request by robrez**
Fix for issue ..
https://github.com/PolymerElements/paper-input/issues/275

paper-input

### CODE REVIEW

**Comment by notwaldorf** [comment]
Thanks!

**Comment by notwaldorf** [comment]
@robrez Argh, unfortunately this causes problems with `<paper-textarea>`, which now acts funky when given a small width, like:
```css
paper-textarea {
  width: 30px;
}
```

**Comment by robrez** [comment]
Oh man! So sorry about that!

##### --paper-input-container-input to the rescue?
I'm thinking, instead of trying to hammer every nail, I could just make use of the `--paper-input-container-input` mixin. I'll try and retest this theory and update my findings.

##### Here are some details about another case that made me worry about the changes from this PR...

This past week I was trying to "fix" gold-cc-input for IE using the flex-basis trick. The overall markup was the same as this case -- gold-cc-input inside a horizontal flex container.
- w/o flex-auto, element was sized way too small
- w/ flex-auto, element was sized correctly
- unless element was explicitly sized (like your case -- width: 200px).
-- When the element was explicitly sized, the paper-input's contents overflow the paper-input's boundry

I was trying to figure some solution to fix all of the problematic-in-ie cases known to me, but I got discouraged and never got back around to it.
Here are some additional changes I was testing out. They seemed to achieve the desired results but I don't feel confident about them at all.

```
      .label-and-input-container {
        @apply(--layout-flex-auto);
        @apply(--layout-relative);
+       width: 100%
+       max-width: 100%
      }
...
      .input-content ::content input,
      .input-content ::content textarea,
      .input-content ::content iron-autogrow-textarea,
      .input-content ::content .paper-input-input {
        position: relative; /* to make a stacking context */
        outline: none;
        box-shadow: none;
        padding: 0;
        width: 100%;
+       max-width: 100%;
        background: transparent;
        border: none;
        color: var(--paper-input-container-input-color, --primary-text-color);
        -webkit-appearance: none;
        text-align: inherit;
        @apply(--paper-font-subhead);
        @apply(--paper-input-container-input);
      }
```

I'm worried that the changes above might also have some adverse effects on `prefix` and/or `suffix`.

These IE-only problems make me :*(
[flexbugs](https://github.com/philipwalton/flexbugs) has been a useful resource

**Comment by robrez** [comment]
Tinkering around today, I added a new mixin to this rule in paper-input-container--

```
      .label-and-input-container {
        @apply(--layout-flex);
        @apply(--layout-relative);
+       @apply(--paper-input-blah);
      }
```

Then elsewhere..

```
    .hdiv {
        @apply(--layout-horizontal);
        @apply(--layout-justified);
        @apply(--layout-wrap);
    }

    paper-input.ie-fix {
      --paper-input-blah: {
        @apply(--layout-flex-auto);
      };
    }
...
    <div class="hdiv">
        <paper-input class="ie-fix" label="text input"></paper-input>
        <paper-input class="ie-fix" label="text input"></paper-input>
    </div>
```

Confirmed this works for the original case.

The other thought I had was making a custom-property for 'width'.
Then a rule in paper-input-container could do something like...
```
      .label-and-input-container {
        @apply(--layout-flex);
        @apply(--layout-relative);
      }

      .label-and-input-container.oh-hai-width {
        flex-basis: var(--paper-input-width);
      }
```

The closest I've come to a rule that makes everything seem to work OK is this one --
```
      .label-and-input-container {
-       @apply(--layout-flex);
+       @apply(--layout-flex-auto);
        @apply(--layout-relative);
+       width: 100%
+       max-width: 100%
      }
```

¯\\_(ツ)_/¯

**Comment by notwaldorf** [comment]
I don't think adding a `--paper-input-width` custom property is a good idea. It's too specific, and the `width` property on the host should already has the same intent.

I think the last thing you said, so adding 
```
.label-and-input-container {
        @apply(--layout-flex-auto);
        @apply(--layout-relative);
        width: 100%;
        max-width: 100%;
      }
```

might make the most sense, and seems to work well. Would you mind sending a PR for that, referencing this PR in the description, please? Thanks!

**Comment by robrez** [comment]
What do you think about these additional changes --

Either:
```

      ::content [prefix] {
        @apply(--paper-font-subhead);
        @apply(--paper-input-prefix);
+       @apply(--layout-flex-none);
      }

      ::content [suffix] {
        @apply(--paper-font-subhead);
        @apply(--paper-input-suffix);
+       @apply(--layout-flex-none);
      }
```
or
```

      ::content [prefix] {
        @apply(--paper-font-subhead);
        @apply(--paper-input-prefix);
+       -ms-flex-shrink: 0;
+       -webkit-flex-shrink: 0;
+       flex-shrink: 0;
      }

      ::content [suffix] {
        @apply(--paper-font-subhead);
        @apply(--paper-input-suffix);
        @apply(--layout-flex-none);
+       -ms-flex-shrink: 0;
+       -webkit-flex-shrink: 0;
+       flex-shrink: 0;
      }
```

Without them, prefix and suffix shrink -- see the top example below.

prefixsuffix

**Comment by robrez** [comment]
Sorry for spamming you --


Also, retesting paper-text area.
Before this PR (and after), placing two paper-textarea elements inside of a horizontal flex parent causes the incorrect "small sizing" problem, even in chrome.

Given this markup..
```
    <demo-snippet class="horizontal">
      <template>
        <paper-textarea label="autoresizing textarea input"></paper-textarea>
        <paper-textarea label="autoresizing textarea input"></paper-textarea>
      </template>
    </demo-snippet>
```

textarea-nosize

With or w/o the previous PR, and even the intended follow-up PR, paper-textarea requires some explicit sizing rule whenever included in a horizontal flex parent..
textarea-sized

I don't think this is something I want to try to fix --
adding a `--flex-auto` to the host rule of `paper-textarea` will give the element size, but prevents the element containing the paper-textarea from setting an explicit size rule eg `width: 50px`.

**Comment by notwaldorf** [comment]
The flex container bug is separate (#299), so you don't have to worry about that. Also, your original PR didn't break that, so it's an unrelated issue that I'll fix. For now, I just want to fix this one breakage :)

I would also hold off the prefix/suffix changes. Maybe send them as a separate PR/issue, since I'm not sure what exactly the problem is (i.e. when do they shrink?)

**Comment by robrez** [comment]
I think they shrink whenever they're iron-icons, I was leaning towards fixing them here because the new rule `width: 100%; max-width: 100%` causes the problem

**Comment by notwaldorf** [comment]
Ohhhh I see. Ok, let's do those too in the same PR, and continue the conversation there (so I can pull the code and test it for a bit. I'm losing track of what the changes are 😟)

**Pull request merged**
