### PR TITLE
remove trailing comma in bower json

### PR DESCRIPTION
**Pull request by TomK**
bower update is broken
image

### CODE REVIEW

**Comment by TomK** [comment]
invalid json was introduced in 842abf69db2766dd2cfabc76a5bb37a999ef3dd6
@leogr, is this what your `typo` comments on the commit are referring to?

**Comment by leogr** [comment]
@TomK yes!

**Comment by TomK** [comment]
@notwaldorf pretty please? 🕺

**Comment by notwaldorf** [comment]
@TomK Sorry, I can't merge PRs in my sleep :)

**Comment by TomK** [comment]
Thank you! Sorry, didn't mean it as a nag, just tagged you for the notification :)

**Pull request merged**
