### PR TITLE
[WIP] Split PaperInputBehavior

### PR DESCRIPTION
**Pull request by abdonrd**
Discuss in #233 issue.

### CODE REVIEW

**Comment by notwaldorf** [comment]
Hmm, I think something with the word 'iron' belongs in an iron repo. `IronInputBehaviour` probably belongs in `iron-input` :)

**Comment by abdonrd** [comment]
Yes, yes, you are right.
I added a TODO in line [16](https://github.com/PolymerElements/paper-input/pull/237/files#diff-f23b14629a50859ed46ba0b937705d35R16): "Move this behavior to IronBehaviors". But maybe `iron-input` is a better place.

**Comment by notwaldorf** [comment]
Don't move it yet. I left a comment on the PR, where I'm having second thoughts about what this should be named. Naming is hard 😢

**Comment by notwaldorf** [comment]
As commented on https://github.com/PolymerElements/paper-input/issues/233, I'm going to close this PR for now, as I don't think it's worth spending time refactoring paper-input at this time.

**Pull request closed without merging**
