### PR TITLE
add min, max, step

### PR DESCRIPTION
**Pull request by jscissr**
For type="number" or "range".
I tried to put them in alphabetically, but it's not really sorted.

### CODE REVIEW

**Comment by jscissr** [comment]
I don't know how to properly set multiple types, so I simply set it to String. (There can be both numbers and dates as strings.)

**Comment by notwaldorf** [comment]
This PR looks fine -- as a style preference, i would put the `min`/`max`/`step` props all together (maybe after minlength)?

**Comment by jscissr** [comment]
I pushed a commit. I also put minlength and maxlength together.

**Comment by notwaldorf** [comment]
Awesome, thanks so much!

**Pull request merged**
