### PR TITLE
Update caret position test to properly fail

### PR DESCRIPTION
**Pull request by jakemac53**
This test should actually be failing, but it was cheating before.

### CODE REVIEW

**Comment by notwaldorf** [comment]
:(

Any chance you know why the test is failing?

**Comment by jakemac53** [comment]
[updateValueAndPreserveCaret](https://github.com/PolymerElements/paper-input/blob/master/paper-input-behavior.html#L340) uses the selection from `inputElement`, where for paper-textarea it should be using `textarea`. Not sure the best way to solve it, overriding the method in paper-textarea possibly?

**Comment by notwaldorf** [comment]
@jakemac53 Ah, figured it out. Created a PR to fix this in `iron-autogrow-textarea`: https://github.com/PolymerElements/iron-autogrow-textarea/pull/35

Once that is merged, I'll rerun the tests and merge this (I feel sketchy about merging all-broken tests. Even though they're correct)

**Comment by jakemac53** [comment]
Sure, I really just sent this out to show that things were broken ;)

**Comment by notwaldorf** [comment]
Closing this, since I fixed the tests in https://github.com/PolymerElements/iron-autogrow-textarea/issues/35

**Comment by jakemac53** [comment]
nice, thanks!

**Pull request closed without merging**
