### PR TITLE
Added support for HTML5 datalists

### PR DESCRIPTION
**Pull request by RNCRyan**
Added support for HTML5 datalists. This pull persists a list property as an attribute to the iron-input input element.

### CODE REVIEW

**Comment by RNCRyan** [comment]
Huzzah; I believe I've finally pleased the googlebot checks.  

Sorry for the pull request spam; I couldn't figure out how to fix an existing pull request, and so I just closed/remade whenever I tried a fix to my PR submission.  Submitting to GitHub is new to me...

**Comment by RNCRyan** [comment]
@morethanreal Any chance I could get this request merged?  Or is there anything I can do to make this PR more appropriate to be merge material?  Thanks.

**Comment by morethanreal** [comment]
lgtm

**Comment by KeithHenry** [comment]
This only works with shady DOM polyfills. An `<input>` in the proper shadow DOM can't reference any `<datalist>` that's in the light DOM, and so fails.

In order to work the `<datalist>` needs to be in the same shadow root as the `<input>`

**Comment by KeithHenry** [comment]
I've raised that as https://github.com/PolymerElements/paper-input/issues/595

**Pull request merged**
