### PR TITLE
Add prefix/suffix to paper-textarea.

### PR DESCRIPTION
**Pull request by b-times-b**
Added prefix/suffix content to paper-textarea in order to have the same feature as on paper-input (as the documentation implies).

### CODE REVIEW

**Comment by notwaldorf** [comment]
How does this work with multiline stuff? Does it align to the top or bottom of the textarea?

**Comment by b-times-b** [comment]
@notwaldorf It aligns at the bottom above the line just like at a single line input. I use it for a decent marker to show markdown support for the text.

**Comment by b-times-b** [comment]
I signed it!
contributors@ax-semantics.com

**Comment by notwaldorf** [comment]
@b-times-b Actually, it seems to align in the middle, which is a bit weird:
screen shot 2016-01-05 at 12 15 55 pm

If it would align to the bottom, that would be fine :)

**Comment by notwaldorf** [comment]
Closing as this PR doesn't seem to be active. Please re-open this when it's ready for another look

**Comment by MarcMouallem** [comment]
This would be really nice. If someone wants to finish it :) Otherwise I'll add it to my tec debt :(

**Pull request closed without merging**
