### PR TITLE
add a disabled property

### PR DESCRIPTION
**Pull request by notwaldorf**
Fixes https://github.com/PolymerElements/paper-input/issues/16

### CODE REVIEW

**Comment by morethanreal** [comment]
Also set `disabled` on the `<iron-input>`?

**Comment by notwaldorf** [comment]
Done!

**Comment by morethanreal** [comment]
BTW, is this styled properly for disabled? I think the underline is dotted for disabled in the spec.

**Comment by notwaldorf** [comment]
Oh, I missed that. Updated! (I took the style from `0.5`)

**Comment by morethanreal** [comment]
lgtm

**Pull request merged**
