### PR TITLE
Fix #364: Make char-counter work with Numbers

### LINKED ISSUE #364: Enhancement: Allow set paper-input-char-counter for number
Configuring paper-input-char-counter for type=number causes error (property length is not defined in number):

```code
Uncaught TypeError: Cannot read property 'toString' of undefined 
Polymer.update	@	paper-input-char-counter.html:86
Polymer.updateAddons	@	paper-input-container.html:563
```

Sometimes we need to allow user to see how many numbers (chars) has typed, for example a phone number with some input pattern (10 digits starting with 3).

```diff
Index: x-app-polymer/src/main/polymer-starter-kit-1.2.3/app/bower_components/paper-input/paper-input-char-counter.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- x-app-polymer/src/main/polymer-starter-kit-1.2.3/app/bower_components/paper-input/paper-input-char-counter.html	(revision )
+++ x-app-polymer/src/main/polymer-starter-kit-1.2.3/app/bower_components/paper-input/paper-input-char-counter.html	(revision )
@@ -83,6 +83,10 @@
 
       state.value = state.value || '';
 
+      if(typeof state.value != 'string') {
+          state.value = state.value.toString();
+      }
+
       var counter = state.value.length.toString();
 
       if (state.inputElement.hasAttribute('maxlength')) {
```

Maybe this is more appropiate:

```diff
Index: x-app-polymer/src/main/polymer-starter-kit-1.2.3/app/bower_components/paper-input/paper-input-char-counter.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- x-app-polymer/src/main/polymer-starter-kit-1.2.3/app/bower_components/paper-input/paper-input-char-counter.html	(revision )
+++ x-app-polymer/src/main/polymer-starter-kit-1.2.3/app/bower_components/paper-input/paper-input-char-counter.html	(revision )
@@ -83,7 +83,13 @@
 
       state.value = state.value || '';
 
-      var counter = state.value.length.toString();
+      var counter;
+
+      if(typeof state.value != 'string') {
+        counter = state.value.toString().length.toString();
+      } else {
+        counter = state.value.length.toString();
+      }
 
       if (state.inputElement.hasAttribute('maxlength')) {
         counter += '/' + state.inputElement.getAttribute('maxlength');
```

### PR DESCRIPTION
**Pull request by rwestlund**
This is a simple fix for issue #364.

### CODE REVIEW

**Comment by rwestlund** [comment]
CLA is signed.

**Comment by rwestlund** [comment]
I'm pretty sure the CI failure isn't my fault.  My change is trivial and the failure says: "Unable to connect to host localhost on port 7055 after 45000 ms."  If there's a way to make it retry, I don't see it.

**Comment by notwaldorf** [comment]
@rwestlund Yeah, the failure isn't your fault. Would you mind adding a test though, that this works correctly for `input type=number`? Thanks!

**Comment by rwestlund** [comment]
The test is in place.

**Pull request merged**
